#!/bin/bash

BUILDER_NAME="gtsam-tmr-builder"
BASE_IMAGES=("amd64/ubuntu:16.04" "arm32v7/ubuntu:18.04")
BUILDER_IMAGES=""

for IMAGE in "${BASE_IMAGES[@]}"; do
    IFS='/' read -ra BASE_ARCH <<< "$IMAGE"
    IFS=':' read -ra IMAGE_ARR <<< "$IMAGE"
    VERSION_TAG="${BASE_ARCH[0]}-${IMAGE_ARR[1]}"
    BUILDER_IMAGE="$BUILDER_NAME-$VERSION_TAG"
    echo "Building: $BUILDER_IMAGE"
    docker build --build-arg base="$IMAGE" . -t "$BUILDER_IMAGE" --label UbuntuVersion="$VERSION_TAG" --add-host repository.net.tmr:10.4.0.1
    BUILDER_IMAGES="$BUILDER_IMAGES $BUILDER_IMAGE"
done

cd ../..

for BUILDER in $BUILDER_IMAGES; do

    UBUNTU_VERSION_FULL="$(docker image inspect "$BUILDER" --format "{{.Config.Labels.UbuntuVersion}}")"
    IFS='-' read -ra UBUNTU_VERSION_SPLIT <<< "$UBUNTU_VERSION_FULL"
    UBUNTU_VERSION="${UBUNTU_VERSION_SPLIT[1]}"
    BUILD_DIR="build-$BUILDER"

    if [ ! -d "$BUILD_DIR" ]; then
        mkdir "$BUILD_DIR"
    fi

    docker run -v $(pwd):/mnt --rm -w=/mnt/"$BUILD_DIR" "$BUILDER" bash -c "cmake -DCMAKE_BUILD_TYPE=Release -DGTSAM_BUILD_WITH_MARCH_NATIVE=OFF -DGTSAM_BUILD_TYPE_POSTFIXES=OFF -DGTSAM_BUILD_UNSTABLE=OFF -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF -DGTSAM_UNSTABLE_BUILD_PYTHON=OFF -DGTSAM_UNSTABLE_INSTALL_MATLAB_TOOLBOX=OFF -DBUILD_SHARED_LIBS=ON -DGTSAM_WITH_TBB=OFF -DGTSAM_WITH_EIGEN_MKL=OFF -DGTSAM_WITH_EIGEN_MKL_OPENMP=OFF -DGTSAM_BUILD_PYTHON=OFF -DGTSAM_INSTALL_MATLAB_TOOLBOX=OFF -DGTSAM_BUILD_WITH_CCACHE=OFF -DGTSAM_USE_SYSTEM_EIGEN=ON -DGTSAM_USE_SYSTEM_METIS=OFF -DGTSAM_USE_BOOST_FEATURES=OFF -DGTSAM_ENABLE_BOOST_SERIALIZATION=OFF .. ; make -j8 check && make -j8 package"
    DEB_PACKAGE=$(ls $BUILD_DIR | grep .deb)
    cp $BUILD_DIR/$DEB_PACKAGE ./tmr_build/$UBUNTU_VERSION-$DEB_PACKAGE

done
